### ISSUE TITLE
Can I use it as an Injector ?

### ISSUE THREAD

**Issue by limpbrains** [acornjs/acorn-class-fields#3]
Hi.

I'm trying to run this plugin with https://github.com/i18next/i18next-parser

Like this
```
const injectAcornStaticClassPropertyInitializer = require('acorn-static-class-property-initializer/inject');
const classFields = require('acorn-class-fields');

const js = [
    {
        lexer: 'JsxLexer',
        attr: 'i18nKey', // Attribute for the keys

        // acorn config (for more information on the acorn options, see here: https://github.com/acornjs/acorn#main-parser)
        acorn: {
            sourceType: 'module',
            ecmaVersion: 10, // forward compatibility
            injectors: [classFields, injectAcornStaticClassPropertyInitializer],
            plugins: { staticClassPropertyInitializer: true, classFields: true }
        }
    }
];

...
```

And I have this error
```

  [read]  /project/frontend/src/app/Market/Chart/index.js
/project/node_modules/i18next-parser/dist/parser.js:70
        }} catch (err) {_didIteratorError = true;_iteratorError = err;} finally {try {if (!_iteratorNormalCompletion && _iterator.return) {_iterator.return();}} finally {if (_didIteratorError) {throw _iteratorError;}}}
                                                                                                                                                                                                  ^

TypeError: Class extends value #<Object> is not a constructor or null
    at module.exports (/project/node_modules/acorn-class-fields/index.js:30:3)
    at /project/node_modules/i18next-parser/dist/lexers/javascript-lexer.js:31:48
    at Array.reduce (<anonymous>)
    at JsxLexer.JavascriptLexer (/project/node_modules/i18next-parser/dist/lexers/javascript-lexer.js:30:34)
    at new JsxLexer (/project/node_modules/i18next-parser/dist/lexers/jsx-lexer.js:36:106)
    at Parser.parse (/project/node_modules/i18next-parser/dist/parser.js:67:23)
    at i18nTransform._transform (/project/node_modules/i18next-parser/dist/transform.js:70:33)
    at i18nTransform.Transform._read (_stream_transform.js:190:10)
    at i18nTransform.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
```

Is this because of a way acorn-class-fields initializes ?
My acorn deps are:
```
    "acorn-class-fields": "^0.2.1",
    "acorn-jsx": "^4.1.1",
    "acorn-stage3": "^0.6.0",
    "acorn-static-class-property-initializer": "^1.0.0",
```

**Comment by adrianheine** [comment]
That's different acorn interfaces your plugins are supporting. I suggest you switch to `acorn-stage3@1.0.0` and `acorn-jsx@5.0.1` and drop the other two (as they are included in `acorn-stage3`).

**Comment by limpbrains** [comment]
I'm using acorn-stage3 because `acorn-jsx@5` doesn't work with i18next-parser (https://github.com/i18next/i18next-parser/issues/136)

Thanks for help

**Comment by adrianheine** [comment]
Oh, right, `i18next-parser` isn't compatible with `acorn@6`, either. The following table shows you the latest version of the packages you use that is compatible with `acorn@5` and `acorn@6`, respectively:

package |acorn@5 | acorn@6
---|---|----
acorn-class-fields | 0.1.2 | 0.2.1
acorn-stage3 | 0.6.0 | 1.0.0
acorn-jsx | 4.1.1 | 5.0.1
i18next-parser | 1.0.0 | _none yet_
acorn-static-class-property-initializer | 1.0.0 | _none yet_

You cannot mix these. I suggest you use `acorn@5` for now and lobby the `i18next-parser` devs to switch to the new plugin interface.
