### ISSUE TITLE
parse error when propertyName is number

### ISSUE THREAD

**Issue by LongTengDao** [acornjs/acorn-class-fields#6]
## field error ( acorn-class-fields )

```js
'use strict';
Error.stackTraceLimit = 100;
require('acorn').Parser.extend( require('acorn-class-fields')                                         ).parse('class X { 1 = 1; }');
```
```
SyntaxError: Unexpected token (1:12)
    at Object.pp$4.raise (/node_modules/acorn/dist/acorn.js:2825:15)
    at Object.pp.unexpected (/node_modules/acorn/dist/acorn.js:689:10)
    at Object.pp.expect (/node_modules/acorn/dist/acorn.js:683:28)
    at Object.pp$3.parseMethod (/node_modules/acorn/dist/acorn.js:2609:10)
    at Object.pp$1.parseClassMethod (/node_modules/acorn/dist/acorn.js:1387:25)
    
    at Object.pp$1.parseClassElement (/node_modules/acorn/dist/acorn.js:1376:10)
    
    at Object.parseClassElement (/node_modules/acorn-class-fields/index.js:49:38)
    
    at Object.pp$1.parseClass (/node_modules/acorn/dist/acorn.js:1315:26)
    at Object.parseClass (/node_modules/acorn-class-fields/node_modules/acorn-private-class-elements/index.js:78:29)
    at Object.pp$1.parseStatement (/node_modules/acorn/dist/acorn.js:833:19)
    at Object.pp$1.parseTopLevel (/node_modules/acorn/dist/acorn.js:746:23)
    at Object.parse (/node_modules/acorn/dist/acorn.js:553:17)
    at Function.parse (/node_modules/acorn/dist/acorn.js:576:37)
    at Object.<anonymous> (/TEST.js:3:105)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
```

## field error ( acorn-class-fields, acorn-static-class-features )

```js
'use strict';
Error.stackTraceLimit = 100;
require('acorn').Parser.extend( require('acorn-class-fields'), require('acorn-static-class-features') ).parse('class X { 1 = 1; }');
```
```
SyntaxError: Unexpected token (1:12)
    at Object.pp$4.raise (/node_modules/acorn/dist/acorn.js:2825:15)
    at Object.pp.unexpected (/node_modules/acorn/dist/acorn.js:689:10)
    at Object.pp.expect (/node_modules/acorn/dist/acorn.js:683:28)
    at Object.pp$3.parseMethod (/node_modules/acorn/dist/acorn.js:2609:10)
    at Object.pp$1.parseClassMethod (/node_modules/acorn/dist/acorn.js:1387:25)
    at Object.parseClassMethod (/node_modules/acorn-static-class-features/index.js:110:39)
    at Object.pp$1.parseClassElement (/node_modules/acorn/dist/acorn.js:1376:10)
    
    at Object.parseClassElement (/node_modules/acorn-class-fields/index.js:49:38)
    at Object.parseClassElement (/node_modules/acorn-static-class-features/index.js:43:56)
    at Object.pp$1.parseClass (/node_modules/acorn/dist/acorn.js:1315:26)
    at Object.parseClass (/node_modules/acorn-class-fields/node_modules/acorn-private-class-elements/index.js:78:29)
    at Object.pp$1.parseStatement (/node_modules/acorn/dist/acorn.js:833:19)
    at Object.pp$1.parseTopLevel (/node_modules/acorn/dist/acorn.js:746:23)
    at Object.parse (/node_modules/acorn/dist/acorn.js:553:17)
    at Function.parse (/node_modules/acorn/dist/acorn.js:576:37)
    at Object.<anonymous> (/TEST.js:3:105)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
```

## field error ( acorn-static-class-features, acorn-class-fields )

```js
'use strict';
Error.stackTraceLimit = 100;
require('acorn').Parser.extend( require('acorn-static-class-features'), require('acorn-class-fields') ).parse('class X { 1 = 1; }');
```
```
SyntaxError: Unexpected token (1:12)
    at Object.pp$4.raise (/node_modules/acorn/dist/acorn.js:2825:15)
    at Object.pp.unexpected (/node_modules/acorn/dist/acorn.js:689:10)
    at Object.pp.expect (/node_modules/acorn/dist/acorn.js:683:28)
    at Object.pp$3.parseMethod (/node_modules/acorn/dist/acorn.js:2609:10)
    at Object.pp$1.parseClassMethod (/node_modules/acorn/dist/acorn.js:1387:25)
    at Object.parseClassMethod (/node_modules/acorn-static-class-features/index.js:110:39)
    at Object.pp$1.parseClassElement (/node_modules/acorn/dist/acorn.js:1376:10)
    at Object.parseClassElement (/node_modules/acorn-static-class-features/index.js:43:56)
    at Object.parseClassElement (/node_modules/acorn-class-fields/index.js:49:38)
    
    at Object.pp$1.parseClass (/node_modules/acorn/dist/acorn.js:1315:26)
    at Object.parseClass (/node_modules/acorn-static-class-features/node_modules/acorn-private-class-elements/index.js:78:29)
    at Object.pp$1.parseStatement (/node_modules/acorn/dist/acorn.js:833:19)
    at Object.pp$1.parseTopLevel (/node_modules/acorn/dist/acorn.js:746:23)
    at Object.parse (/node_modules/acorn/dist/acorn.js:553:17)
    at Function.parse (/node_modules/acorn/dist/acorn.js:576:37)
    at Object.<anonymous> (/TEST.js:3:105)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
```

## static right

There is no error when parse `class X { static 1 = 1; }`.

**Comment by adrianheine** [comment]
Fixed in 5120125ca6dfc0059ff4387716aabba87e424496.
